

services:
  db: #service name
    image: postgres:15 # image name and version
    container_name: postgres-db # Name of the container
    environment: #database parameters
      POSTGRES_USER: apts-admin
      POSTGRES_PASSWORD: FakePwd13#
      POSTGRES_DB: apartments
    ports:
      - "5433:5432" # Map container port 5432 to local port 5433, use 5433 since 5432 is probably occupied by local postgres instance
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
    networks:
      - app-network # Ensure networking between services

volumes:
  db_data: # Named volume for persistence
  
networks:
  app-network: # Custom network for services