# Set the base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Copy the wait-for-it.sh script into the container
COPY wait-for-it.sh /wait-for-it.sh

# Make the script executable
RUN chmod +x /wait-for-it.sh

# Compile typescript to /dist
RUN npm run build 

# Expose the port the app runs on
EXPOSE 3000

# Start the app: Wait for database, run migrations, then start the app
CMD /wait-for-it.sh postgres-db:5432 -- npm run db:migrate && npm run dev