# Set the base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Compile typescript to /dist
RUN npm run build 

# Expose the port the app runs on
EXPOSE 3000

# Start the app: Wait for database, run migrations, then start the app
CMD npm run dev